logo: Anime Reviews
title: Anime Reviews
description: > # this means to ignore newlines until "baseurl:"
  Anime Reviews about the latest season
permalink: ':title/'
baseurl: "/AnimeReviews" # the subpath of your site, e.g. /blog
url: "https://dreanoranime.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: holo.mp4
banner-title: Hello fellow degenerate
banner-desc: #

# Author settings
author-pic: face.png
author-name: Dreanor 
about-author: This blog mostly will be about short recaps/reviews of everything that aired each season. I watched over 2800 different anime at this point and Iâ€™ll likely never stop.
website: https://dreanoranime.github.io/AnimeReviews


# Disqus
discus_identifier: dreanoranimereviews # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap


include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
